import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

// ─── Lab definitions (mirrors StepLabResults.jsx) ────────────────────────────

const LAB_DEFS = [
  { field: 'wbc',         label: 'White Blood Cell Count',    unit: '10³ cells/µL', ref: '4.5 – 11.0',         refMin: 4.5,  refMax: 11.0 },
  { field: 'hemoglobin',  label: 'Hemoglobin',                unit: 'g/dL',         ref: 'M: 13.5–17.5 / F: 12–16' },
  { field: 'platelets',   label: 'Platelet Count',            unit: '10³/µL',       ref: '150 – 400',           refMin: 150,  refMax: 400  },
  { field: 'cholesterol', label: 'Total Cholesterol',         unit: 'mg/dL',        ref: '< 200 (desirable)',   refMax: 200  },
  { field: 'hba1c',       label: 'HbA1c (Glycated Hemoglobin)', unit: '%',          ref: '< 5.7 (normal)',      refMax: 5.7  },
  { field: 'crp',         label: 'C-Reactive Protein (CRP)', unit: 'mg/L',         ref: '< 1.0 (optimal)',     refMax: 1.0  },
  { field: 'psa',         label: 'PSA (Prostate Specific Ag)', unit: 'ng/mL',       ref: '< 4.0',               refMax: 4.0  },
]

const RISK_LABELS = { low: 'Low', moderate: 'Moderate', high: 'High', very_high: 'Very High' }

// ─── Shared header / footer ───────────────────────────────────────────────────

function addHeader(doc, title, subtitle) {
  const W = doc.internal.pageSize.getWidth()

  // Blue header bar
  doc.setFillColor(37, 99, 235)
  doc.rect(0, 0, W, 22, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('PROGNOS', 14, 14)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('AI-Powered Cancer Risk Predictor', 14, 20)

  // Title area
  doc.setTextColor(30, 41, 59)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(title, 14, 34)

  if (subtitle) {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 116, 139)
    doc.text(subtitle, 14, 41)
  }

  // Divider
  doc.setDrawColor(226, 232, 240)
  doc.line(14, 44, W - 14, 44)

  return 50 // y position after header
}

function addFooter(doc) {
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()

  doc.setFillColor(248, 250, 252)
  doc.rect(0, H - 16, W, 16, 'F')

  doc.setFontSize(7)
  doc.setTextColor(148, 163, 184)
  doc.setFont('helvetica', 'normal')
  doc.text(
    'DISCLAIMER: This document is for informational and educational purposes only. It is not medical advice, diagnosis, or treatment.',
    14, H - 9
  )
  doc.text(
    `Generated by Prognos  •  ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`,
    W - 14, H - 9,
    { align: 'right' }
  )
}

// ─── Lab status helper ────────────────────────────────────────────────────────

function getLabStatus(def, value) {
  const v = parseFloat(value)
  if (isNaN(v)) return { label: 'Not provided', color: [148, 163, 184] }
  if (def.refMin !== undefined && v < def.refMin) return { label: 'Below range', color: [234, 179, 8]   }
  if (def.refMax !== undefined && v > def.refMax) return { label: 'Above range', color: [239, 68,  68]  }
  return                                                  { label: 'Normal',       color: [34,  197, 94]  }
}

// ─── Export: Lab Results PDF ─────────────────────────────────────────────────

export function downloadLabResultsPDF(labData = {}, assessmentId) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const date = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })

  let y = addHeader(doc, 'Laboratory & Blood Test Summary', `Assessment date: ${date}`)

  // Intro text
  doc.setFontSize(9)
  doc.setTextColor(71, 85, 105)
  doc.setFont('helvetica', 'normal')
  doc.text(
    'The table below shows the blood test values you reported during your health assessment,\nalong with standard reference ranges for comparison.',
    14, y
  )
  y += 14

  // Table rows
  const rows = LAB_DEFS.map(def => {
    const raw    = labData[def.field]
    const value  = raw ? String(raw) : '—'
    const status = getLabStatus(def, raw)
    return [def.label, value, def.unit, def.ref, status]
  })

  autoTable(doc, {
    startY: y,
    head: [['Test Name', 'Your Value', 'Unit', 'Reference Range', 'Status']],
    body: rows.map(r => r.slice(0, 4).concat(r[4].label)),
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: { fontSize: 8.5, textColor: [30, 41, 59] },
    columnStyles: {
      0: { cellWidth: 62 },
      1: { cellWidth: 24, halign: 'center' },
      2: { cellWidth: 26, halign: 'center' },
      3: { cellWidth: 46 },
      4: { cellWidth: 28, halign: 'center' },
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    didDrawCell: (data) => {
      // Color-code the status column
      if (data.section === 'body' && data.column.index === 4) {
        const status = rows[data.row.index]?.[4]
        if (status) {
          doc.setTextColor(...status.color)
          doc.setFont('helvetica', 'bold')
          doc.text(
            status.label,
            data.cell.x + data.cell.width / 2,
            data.cell.y + data.cell.height / 2 + 1,
            { align: 'center' }
          )
          doc.setTextColor(30, 41, 59)
          doc.setFont('helvetica', 'normal')
        }
      }
    },
    margin: { left: 14, right: 14 },
  })

  y = doc.lastAutoTable.finalY + 10

  // Notes box
  doc.setFillColor(239, 246, 255)
  doc.setDrawColor(191, 219, 254)
  doc.roundedRect(14, y, doc.internal.pageSize.getWidth() - 28, 28, 2, 2, 'FD')

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 64, 175)
  doc.text('Important Notes', 19, y + 7)

  doc.setFont('helvetica', 'normal')
  doc.setTextColor(55, 65, 81)
  doc.text([
    '• Reference ranges are general population averages. Your doctor may use different ranges based on age, sex, or lab.',
    '• Values marked "Above range" or "Below range" do not necessarily indicate disease — consult your healthcare provider.',
    '• Values shown are self-reported and have not been verified by a medical laboratory.',
  ], 19, y + 13, { lineHeightFactor: 1.6 })

  addFooter(doc)

  const filename = assessmentId
    ? `prognos-lab-results-${assessmentId.slice(0, 8)}.pdf`
    : `prognos-lab-results-${Date.now()}.pdf`
  doc.save(filename)
}

// ─── Export: Full Risk Report PDF ────────────────────────────────────────────

export function downloadFullReportPDF(result, assessmentId) {
  const doc  = new jsPDF({ unit: 'mm', format: 'a4' })
  const W    = doc.internal.pageSize.getWidth()
  const date = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
  const pct  = Math.round(result.overall_risk ?? 0)
  const key  = result.risk_category || (pct < 15 ? 'low' : pct < 30 ? 'moderate' : pct < 50 ? 'high' : 'very_high')

  let y = addHeader(doc, 'Cancer Risk Assessment Report', `Assessment date: ${date}`)

  // ── Overall risk box ──
  const riskColors = {
    low:      [240, 253, 244],
    moderate: [254, 252, 232],
    high:     [255, 247, 237],
    very_high:[254, 242, 242],
  }
  const riskBorder = {
    low:      [134, 239, 172],
    moderate: [253, 224, 71],
    high:     [253, 186, 116],
    very_high:[252, 165, 165],
  }
  const riskText = {
    low:      [21, 128, 61],
    moderate: [133, 77, 14],
    high:     [154, 52, 18],
    very_high:[185, 28, 28],
  }

  doc.setFillColor(...(riskColors[key] || riskColors.low))
  doc.setDrawColor(...(riskBorder[key] || riskBorder.low))
  doc.roundedRect(14, y, W - 28, 26, 3, 3, 'FD')

  doc.setFontSize(28)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...(riskText[key] || riskText.low))
  doc.text(`${pct}%`, 30, y + 18)

  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text(RISK_LABELS[key] ? `${RISK_LABELS[key]} Risk` : 'Risk Score', 55, y + 12)

  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(71, 85, 105)
  doc.text('Composite score across all 8 cancer types analysed.', 55, y + 19)

  y += 32

  // ── Cancer breakdown table ──
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(15, 23, 42)
  doc.text('Risk Breakdown by Cancer Type', 14, y)
  y += 6

  const breakdown = result.cancer_breakdown || {}
  const sorted = Object.entries(breakdown).sort((a, b) => (b[1].risk_score || 0) - (a[1].risk_score || 0))

  autoTable(doc, {
    startY: y,
    head: [['Cancer Type', 'Risk Score', 'Risk Level', 'Top Contributing Factors']],
    body: sorted.map(([type, d]) => [
      d.label || type,
      `${Math.round(d.risk_score || 0)}%`,
      RISK_LABELS[d.risk_level] || d.risk_level || '—',
      (d.top_factors || []).slice(0, 3).join(' · ') || 'Baseline population risk',
    ]),
    headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 8.5, textColor: [30, 41, 59] },
    columnStyles: {
      0: { cellWidth: 44 },
      1: { cellWidth: 22, halign: 'center' },
      2: { cellWidth: 28, halign: 'center' },
      3: { cellWidth: 82 },
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    didDrawCell: (data) => {
      if (data.section === 'body' && data.column.index === 2) {
        const rk = sorted[data.row.index]?.[1]?.risk_level
        const colors = { low: [21,128,61], moderate: [133,77,14], high: [154,52,18], very_high: [185,28,28] }
        if (rk && colors[rk]) {
          doc.setTextColor(...colors[rk])
          doc.setFont('helvetica', 'bold')
          doc.text(
            RISK_LABELS[rk] || rk,
            data.cell.x + data.cell.width / 2,
            data.cell.y + data.cell.height / 2 + 1,
            { align: 'center' }
          )
          doc.setTextColor(30, 41, 59)
          doc.setFont('helvetica', 'normal')
        }
      }
    },
    margin: { left: 14, right: 14 },
  })

  y = doc.lastAutoTable.finalY + 10

  // ── Top recommendations for highest-risk cancer ──
  const topCancer = sorted[0]
  if (topCancer && topCancer[1].recommendations?.length) {
    const [topType, topData] = topCancer
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 23, 42)
    doc.text(`Key Recommendations — ${topData.label || topType}`, 14, y)
    y += 5

    autoTable(doc, {
      startY: y,
      body: topData.recommendations.slice(0, 5).map(r => [`✓  ${r}`]),
      bodyStyles: { fontSize: 8.5, textColor: [30, 41, 59] },
      columnStyles: { 0: { cellWidth: W - 28 } },
      alternateRowStyles: { fillColor: [240, 253, 244] },
      margin: { left: 14, right: 14 },
    })

    y = doc.lastAutoTable.finalY + 8
  }

  // ── Mock notice ──
  if (result.mock) {
    doc.setFillColor(255, 251, 235)
    doc.setDrawColor(253, 230, 138)
    doc.roundedRect(14, y, W - 28, 10, 2, 2, 'FD')
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(146, 64, 14)
    doc.text('DEMONSTRATION DATA: ML models not yet trained. Scores are generated by a statistical mock model.', 17, y + 6.5)
  }

  addFooter(doc)

  const filename = assessmentId
    ? `prognos-risk-report-${assessmentId.slice(0, 8)}.pdf`
    : `prognos-risk-report-${Date.now()}.pdf`
  doc.save(filename)
}
